apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastropromocao-deployment
  namespace: cadastropromocao-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cadastropromocao
  template:
    metadata:
      annotations:
        redeploy-at: "2025-07-10T01:42:20Z"
      labels:
        app: cadastropromocao
    spec:
      containers:
      - name: cadastropromocao
        image: eurival/cadastropromocao-frontend:latest  # Alterar conforme a imagem que você está utilizando
        ports:
        - containerPort: 80
        env:
        # 1. Endereço interno da API
        - name: VITE_API_BASE_URL
          value: "https://cinexapi.ingressocinex.com.br"
        # 2. Usuário da API, lido do Secret
        - name: VITE_API_USERNAME
          valueFrom:
            secretKeyRef:
              name: cadastropromocao-api-credentials
              key: API_USERNAME
        # 3. Senha da API, lida do Secret
        - name: VITE_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cadastropromocao-api-credentials
              key: API_PASSWORD
        resources:
          requests:
            memory: "128Mi"           # Requisição de memória (mínimo necessário)
            cpu: "100m"              # Requisição de CPU (mínimo necessário)
            ephemeral-storage: "100Mi"  # Requisição de armazenamento efêmero
          limits:
            memory: "512Mi"           # Limite de memória (máximo permitido)
            cpu: "500m"               # Limite de CPU (máximo permitido)
            ephemeral-storage: "500Mi"  # Limite de armazenamento efêmero
      imagePullPolicy: Always  # Sempre puxa a imagem mais recente