apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastropromocao-deployment
  namespace: cadastropromocao-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cadastropromocao
  template:
    metadata:
      annotations:
        redeploy-at: "2025-07-09T02:27:20Z"
      labels:
        app: cadastropromocao
    spec:
      containers:
      - name: cadastropromocao
        image: public.ecr.aws/t6g4w7z5/cadastropromocao-frontend:latest
        ports:
        - containerPort: 80
        env:
        # 1. Endereço interno da API
        - name: VITE_API_BASE_URL
          value: "https://cinexapi.ingressocinex.com.br"
        # 2. Usuário da API, lido do Secret
        - name: VITE_API_USERNAME
          valueFrom:
            secretKeyRef:
              name: cadastropromocao-api-credentials
              key: API_USERNAME
        # 3. Senha da API, lida do Secret
        - name: VITE_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cadastropromocao-api-credentials
              key: API_PASSWORD