apiVersion: v1
kind: Secret
metadata:
  name: cadastropromocao-api-credentials
  namespace: cadastropromocao-apps
type: Opaque
stringData:
  # Coloque aqui o usuário e a senha que sua API espera.
  API_USERNAME: "admin"
  API_PASSWORD: "admin"