 
services:
  cinexapi:
    image: eurival/cinexapi:latest  # Substitua pela sua imagem JHipster
    container_name: cinexapi
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8080:8080'
    networks:
      - cinexnet

  frontend:
    build: .
    container_name: cadastropromocao-frontend
    depends_on:
      - cinexapi
    ports:
      - '5173:80'
    networks:
      - cinexnet

networks:
  cinexnet:
    driver: bridge
