apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cadastropromocao-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eurival/cadastropromocao' 
    targetRevision: main
    path: infra/kubernets 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cadastropromocao-apps 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true